# .gitlab-ci.yml
# SEE: https://gitlab.com/gitlab-examples/nodejs/blob/master/.gitlab-ci.yml
# https://gist.github.com/thornbill/b4f44ac81106fd539d5f493a269bf25b
# https://gitlab.com/nfreear/gaad-widget/settings/ci_cd

image: node:6

cache:
  paths:
  - node_modules/

stages:
  - test

job 1:
  stage: test
  script:
   - node -v
   - npm -v
   - npm install
   - npm run build
   - npm test
  after_script:
   - nvm --version
#  tags:
#    - docker

# End.
