language: node_js

node_js: 6

git:
  depth: 8

install: npm install

before_script: num run build

script: npm test

after_script:
  - ls -alh dist
  - ls -alh data
  - cat dist/gaad-widget.min.js

# End.
