language: node_js
node_js:
  - "4"

git:
  depth: 5

install:
  - npm install
  - npm run install-legacy-datejs

script:
  - npm run build
  - npm test

after_script:
  #- ls -alh build
  #- ls -alh data
  - cat build/GAAD.widget.js

# End.
